-- Создание базы данных
CREATE DATABASE IF NOT EXISTS module7;
USE module7;
--первый
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
START TRANSACTION;

SELECT id, name FROM teachers;
DELETE FROM teachers WHERE id = 11;
ROLLBACK;
SELECT id, name FROM teachers;

--второй
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
START TRANSACTION;
UPDATE teachers SET name='Кукушкинд' WHERE id=11;
SELECT name,id FROM teachers WHERE id=11;
COMMIT;

SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
UPDATE teachers SET name='Пупкинд' WHERE id=11;

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
INSERT INTO courses (title) VALUES ('Новый курсец');
SELECT title FROM courses;